package com.zeiv.emp.domain;

// Generated 2014. 5. 3 오후 9:29:17 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * EmployeesAllAttrViewId generated by hbm2java
 */
public class EmployeesAllAttrViewId implements java.io.Serializable {

	private Integer	empNo;
	private String	firstName;
	private String	lastName;
	private String	gender;
	private Date	hireDate;
	private Date	birthDate;
	private String	deptNo;
	private Date	deptFromDate;
	private Date	deptToDate;
	private String	title;
	private Date	titleFromDate;
	private Date	titleToDate;

	public EmployeesAllAttrViewId() {
	}

	public EmployeesAllAttrViewId(Integer empNo, String firstName, String lastName, String gender, Date hireDate, Date birthDate,
			String deptNo, Date deptFromDate, Date deptToDate, String title, Date titleFromDate, Date titleToDate) {
		this.empNo = empNo;
		this.firstName = firstName;
		this.lastName = lastName;
		this.gender = gender;
		this.hireDate = hireDate;
		this.birthDate = birthDate;
		this.deptNo = deptNo;
		this.deptFromDate = deptFromDate;
		this.deptToDate = deptToDate;
		this.title = title;
		this.titleFromDate = titleFromDate;
		this.titleToDate = titleToDate;
	}

	public Integer getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(Integer empNo) {
		this.empNo = empNo;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getHireDate() {
		return this.hireDate;
	}

	public void setHireDate(Date hireDate) {
		this.hireDate = hireDate;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public String getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(String deptNo) {
		this.deptNo = deptNo;
	}

	public Date getDeptFromDate() {
		return this.deptFromDate;
	}

	public void setDeptFromDate(Date deptFromDate) {
		this.deptFromDate = deptFromDate;
	}

	public Date getDeptToDate() {
		return this.deptToDate;
	}

	public void setDeptToDate(Date deptToDate) {
		this.deptToDate = deptToDate;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getTitleFromDate() {
		return this.titleFromDate;
	}

	public void setTitleFromDate(Date titleFromDate) {
		this.titleFromDate = titleFromDate;
	}

	public Date getTitleToDate() {
		return this.titleToDate;
	}

	public void setTitleToDate(Date titleToDate) {
		this.titleToDate = titleToDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmployeesAllAttrViewId))
			return false;
		EmployeesAllAttrViewId castOther = (EmployeesAllAttrViewId) other;

		return ((this.getEmpNo() == castOther.getEmpNo()) || (this.getEmpNo() != null && castOther.getEmpNo() != null && this.getEmpNo()
				.equals(castOther.getEmpNo())))
				&& ((this.getFirstName() == castOther.getFirstName()) || (this.getFirstName() != null && castOther.getFirstName() != null && this
						.getFirstName().equals(castOther.getFirstName())))
				&& ((this.getLastName() == castOther.getLastName()) || (this.getLastName() != null && castOther.getLastName() != null && this
						.getLastName().equals(castOther.getLastName())))
				&& ((this.getGender() == castOther.getGender()) || (this.getGender() != null && castOther.getGender() != null && this
						.getGender().equals(castOther.getGender())))
				&& ((this.getHireDate() == castOther.getHireDate()) || (this.getHireDate() != null && castOther.getHireDate() != null && this
						.getHireDate().equals(castOther.getHireDate())))
				&& ((this.getBirthDate() == castOther.getBirthDate()) || (this.getBirthDate() != null && castOther.getBirthDate() != null && this
						.getBirthDate().equals(castOther.getBirthDate())))
				&& ((this.getDeptNo() == castOther.getDeptNo()) || (this.getDeptNo() != null && castOther.getDeptNo() != null && this
						.getDeptNo().equals(castOther.getDeptNo())))
				&& ((this.getDeptFromDate() == castOther.getDeptFromDate()) || (this.getDeptFromDate() != null
						&& castOther.getDeptFromDate() != null && this.getDeptFromDate().equals(castOther.getDeptFromDate())))
				&& ((this.getDeptToDate() == castOther.getDeptToDate()) || (this.getDeptToDate() != null
						&& castOther.getDeptToDate() != null && this.getDeptToDate().equals(castOther.getDeptToDate())))
				&& ((this.getTitle() == castOther.getTitle()) || (this.getTitle() != null && castOther.getTitle() != null && this
						.getTitle().equals(castOther.getTitle())))
				&& ((this.getTitleFromDate() == castOther.getTitleFromDate()) || (this.getTitleFromDate() != null
						&& castOther.getTitleFromDate() != null && this.getTitleFromDate().equals(castOther.getTitleFromDate())))
				&& ((this.getTitleToDate() == castOther.getTitleToDate()) || (this.getTitleToDate() != null
						&& castOther.getTitleToDate() != null && this.getTitleToDate().equals(castOther.getTitleToDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEmpNo() == null ? 0 : this.getEmpNo().hashCode());
		result = 37 * result + (getFirstName() == null ? 0 : this.getFirstName().hashCode());
		result = 37 * result + (getLastName() == null ? 0 : this.getLastName().hashCode());
		result = 37 * result + (getGender() == null ? 0 : this.getGender().hashCode());
		result = 37 * result + (getHireDate() == null ? 0 : this.getHireDate().hashCode());
		result = 37 * result + (getBirthDate() == null ? 0 : this.getBirthDate().hashCode());
		result = 37 * result + (getDeptNo() == null ? 0 : this.getDeptNo().hashCode());
		result = 37 * result + (getDeptFromDate() == null ? 0 : this.getDeptFromDate().hashCode());
		result = 37 * result + (getDeptToDate() == null ? 0 : this.getDeptToDate().hashCode());
		result = 37 * result + (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result + (getTitleFromDate() == null ? 0 : this.getTitleFromDate().hashCode());
		result = 37 * result + (getTitleToDate() == null ? 0 : this.getTitleToDate().hashCode());
		return result;
	}

}
