package com.zeiv.emp.domain;

// Generated 2014. 5. 3 오후 9:29:17 by Hibernate Tools 4.0.0

/**
 * EmployeesAllAttrView generated by hbm2java
 */
public class EmployeesAllAttrView implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 5939119693639622817L;
	private EmployeesAllAttrViewId	id;

	public EmployeesAllAttrView() {
	}

	public EmployeesAllAttrView(EmployeesAllAttrViewId id) {
		this.id = id;
	}

	public EmployeesAllAttrViewId getId() {
		return this.id;
	}

	public void setId(EmployeesAllAttrViewId id) {
		this.id = id;
	}

}
