package com.zeiv.emp.domain;


// Generated 2014. 5. 4 오전 12:17:16 by Hibernate Tools 4.0.0

/**
 * EmployeesAllAttrView generated by hbm2java
 */
public class EmployeesAllAttrView implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 2390500838402398499L;
	private EmployeesAllAttrViewId	id;

	public EmployeesAllAttrView() {
	}

	public EmployeesAllAttrView(EmployeesAllAttrViewId id) {
		this.id = id;
	}

	public EmployeesAllAttrViewId getId() {
		return this.id;
	}

	public void setId(EmployeesAllAttrViewId id) {
		this.id = id;
	}

}
